PROJECT_NAME := coap_server

# CoAP library component
EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common

# Obligatory global makefile (SDK stuff)
include $(IDF_PATH)/make/project.mk

